[package]
edition = "2021"
name = "bytes4-hound-rs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
ethers = "2.0"
eyre = "0.6"
tokio = {version = "1", features = ["full"]}
